import { v4 as uuid } from "uuid";
/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */
export const videos = [
  {
    _id: "cdf6f607-603d-4ace-b547-328bac18eb1a",
    category: "Something",
    videoId: "qZRSVtxmf88",
    title: "Specified key was too long error  ( Laravel Error )",
    description:
      'In this video . I will show you. How to solve this error " Specified key was too long error" . Copy and paste these line into your ...',
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/qZRSVtxmf88/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/qZRSVtxmf88/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/qZRSVtxmf88/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 46,
    views: 305,
  },
  {
    _id: "a6092fa3-2397-4a66-ab69-259e6f22e30a",
    category: "Something",
    videoId: "ODPI6H8QPjE",
    title: "CodeIgniter Tutorial Part 1. Introduction",
    description:
      "In this YouTube video , I'm Starting CodeIgniter Tutorial . To read more, check my blog post on medium Links: ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/ODPI6H8QPjE/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/ODPI6H8QPjE/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/ODPI6H8QPjE/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 619,
    views: 660,
  },
  {
    _id: "035a2cba-43eb-4ede-9516-bde594c3f491",
    category: "Something",
    videoId: "V_Zk9R1msBI",
    title: "Hide .php or .html extension in url (.htaccess)",
    description:
      "How to remove .php, .html, .htm extension with .htaccess file. Code : RewriteEngine on RewriteCond ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/V_Zk9R1msBI/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/V_Zk9R1msBI/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/V_Zk9R1msBI/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 590,
    views: 272,
  },
  {
    _id: "1243d55c-dca2-475c-a5a3-ccaa023ca2d6",
    category: "Something",
    videoId: "Pel34u7-8-k",
    title: "How to autoload PHP classes the Composer way.",
    description:
      'Today we will learn About: - "How to autoload PHP classes the Composer way." Or "How to Implement PSR-4 in your project.',
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/Pel34u7-8-k/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/Pel34u7-8-k/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/Pel34u7-8-k/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 771,
    views: 788,
  },
  {
    _id: "c17b3b03-5325-444f-86ad-47e89e477a57",
    category: "Something",
    videoId: "1OCOSMplh0I",
    title:
      "How to run php code without installing apache or xampp or wampserver.",
    description:
      "how to run php code without installing apache or xampp or wampserver. a. First, Open Project Directory Or Working directory. b.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/1OCOSMplh0I/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/1OCOSMplh0I/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/1OCOSMplh0I/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 700,
    views: 504,
  },
  {
    _id: "460e4464-ff35-4c68-8f1a-87bc0cd1ca2c",
    category: "Something",
    videoId: "tbl8-6FkvZw",
    title: "Free website hosting sites 2018",
    description:
      "Today We will talk about the latest free hosting providers of 2018. there are many websites hosting providers 1.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/tbl8-6FkvZw/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/tbl8-6FkvZw/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/tbl8-6FkvZw/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 609,
    views: 470,
  },
  {
    _id: "5a04c1f4-d213-4108-a228-783711427cde",
    category: "Something",
    videoId: "3e98ieUNav0",
    title: "How to Display php errors",
    description:
      "How to Display and Log PHP Errors 1. For solution use these method. 2.Create an htaccess file and Some code written in that file ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/3e98ieUNav0/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/3e98ieUNav0/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/3e98ieUNav0/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 210,
    views: 921,
  },
  {
    _id: "a7a391d4-da21-4c54-80e3-0b11151f82d2",
    category: "Something",
    videoId: "AkOBuIyRuq8",
    title: "name &#39;messagebox&#39; is not defined",
    description:
      "Python error solving using add one line code : from tkinter import messagebox This type error Called nameError. Python Error ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/AkOBuIyRuq8/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/AkOBuIyRuq8/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/AkOBuIyRuq8/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 173,
    views: 159,
  },
  {
    _id: "3c319258-9465-4092-8f16-c974271c2a51",
    category: "Something",
    videoId: "5cMIP7ehHGM",
    title: "undefined index:  in php",
    description:
      "How to fix 'Notice Undefined index' in PHP form action Solution for Notice: Undefined index: in index.php Thank's for watching.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/5cMIP7ehHGM/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/5cMIP7ehHGM/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/5cMIP7ehHGM/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 784,
    views: 939,
  },
  {
    _id: "a103c363-19dd-4fda-96b4-d542afb6f340",
    category: "Something",
    videoId: "PbHqmFZ0Tjw",
    title: "How do I get my menu bar back in Sublime Text 3",
    description:
      "How do I get my menu bar back in Sublime Text For This Ctrl+shift+p Press the key together and enter menu Hide/Unhide Menu ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/PbHqmFZ0Tjw/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/PbHqmFZ0Tjw/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/PbHqmFZ0Tjw/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 924,
    views: 736,
  },
  {
    _id: "f8d76d38-183f-4846-ac41-b3975f0cdc92",
    category: "Something",
    videoId: "lTEGpzFZhyc",
    title: "how to install pip on windows",
    description:
      "Python link - https://www.python.org/downloads/ Pip link - https://pip.pypa.io/en/stable/installing/ direct Pip Link ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/lTEGpzFZhyc/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/lTEGpzFZhyc/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/lTEGpzFZhyc/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 663,
    views: 852,
  },
  {
    _id: "7c8b7913-753c-4955-8d99-ff9e7251019f",
    category: "Something",
    videoId: "MRVHxQ2SiOM",
    title: "Cannot find module in node.js",
    description:
      "What's issue Cannot find module Just Type command in terminal or command prompt npm install package-name Thank's for ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/MRVHxQ2SiOM/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/MRVHxQ2SiOM/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/MRVHxQ2SiOM/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 860,
    views: 3,
  },
  {
    _id: "e7d5db10-f243-4a4d-af38-3c146e1e63c8",
    category: "Something",
    videoId: "s34U7b8ecpU",
    title: "How do i take code from codepen and use it locally  ?",
    description: "How do i take code from codepen and use it locally.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/s34U7b8ecpU/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/s34U7b8ecpU/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/s34U7b8ecpU/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 201,
    views: 194,
  },
  {
    _id: "522da569-baf4-4d9e-b493-9fbb4e7620bf",
    category: "Something",
    videoId: "X1_HA0Ts_0o",
    title: "My javascript code is not working ?",
    description:
      "error that come when run javascript code : My javascript code is not working solution for that : // example 1 ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/X1_HA0Ts_0o/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/X1_HA0Ts_0o/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/X1_HA0Ts_0o/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 619,
    views: 605,
  },
  {
    _id: "151109c0-2736-48ca-ac82-96e7e379df2d",
    category: "Something",
    videoId: "7UT2hINdsGU",
    title: "Refused to execute inline event handler in chrome extension",
    description:
      "problem : chrome extension Refused to execute inline event handler because it violates the following Content Security Policy ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/7UT2hINdsGU/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/7UT2hINdsGU/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/7UT2hINdsGU/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 840,
    views: 301,
  },
  {
    _id: "97480795-8e42-4e34-99bd-373f7481eb00",
    category: "Something",
    videoId: "o5wjfyRjvjs",
    title:
      "error: pathspec &#39;commit&#39;&#39; did not match any file(s) known to git.",
    description:
      "Django error: pathspec 'commit'' did not match any file(s) known to git.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/o5wjfyRjvjs/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/o5wjfyRjvjs/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/o5wjfyRjvjs/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 329,
    views: 658,
  },
  {
    _id: "860531fb-51da-4b99-9b0e-9c725988a7bb",
    category: "Something",
    videoId: "8uCS4BqbQQ4",
    title: "src refspec master does not match any.",
    description: "python error that is src refspec master does not match any.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/8uCS4BqbQQ4/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/8uCS4BqbQQ4/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/8uCS4BqbQQ4/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 898,
    views: 980,
  },
  {
    _id: "9f6f92a7-6962-4153-9435-8ef4b57cc961",
    category: "Something",
    videoId: "9foBf9QHSws",
    title: "No Module Named bs4 (BeautifulSoup)",
    description:
      "this python error will be generated when we are not installing BeautifulSoup4 module. for this run this command.... pip install ...",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/9foBf9QHSws/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/9foBf9QHSws/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/9foBf9QHSws/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 48,
    views: 284,
  },
  {
    _id: "9038d707-fe17-4f2c-ac82-93e984b76dc1",
    category: "Something",
    videoId: "2GpfmrdDOFQ",
    title: "No module named request",
    description: "Error : Explain this Django error.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/2GpfmrdDOFQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/2GpfmrdDOFQ/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/2GpfmrdDOFQ/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 436,
    views: 290,
  },
  {
    _id: "5e4762b4-f20f-459d-90cd-e8d16ed9ec4c",
    category: "Something",
    videoId: "TFfrrEBhorQ",
    title: "table &quot;django_content_type&quot; already exists",
    description:
      'django error : table "django_content_type" already exists command : python manage.py migrate --fake-initial.',
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/TFfrrEBhorQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/TFfrrEBhorQ/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/TFfrrEBhorQ/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 817,
    views: 884,
  },
  {
    _id: "28d47911-4fbd-4763-95a4-89bcec64e10e",
    category: "Something",
    videoId: "Kpt-_xhCkEA",
    title: "A server error occurred.  Please contact the administrator.",
    description:
      "django problem solving that are django-improperlyconfigured-module-django-contrib-auth-middleware or A server error occurred.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/Kpt-_xhCkEA/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/Kpt-_xhCkEA/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/Kpt-_xhCkEA/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 605,
    views: 212,
  },
  {
    _id: "cbb370a4-b3d1-4bfc-a053-8360efa88640",
    category: "Something",
    videoId: "awF-WnIALZc",
    title: "SOUTH_DATABASE_ADAPTERS for my Django app that uses South",
    description:
      "How should I be setting SOUTH_DATABASE_ADAPTERS for my Django app that uses South?",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/awF-WnIALZc/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/awF-WnIALZc/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/awF-WnIALZc/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 196,
    views: 766,
  },
  {
    _id: "c2e91ac5-182e-4fa4-9822-ff9a3a4ce87d",
    category: "Something",
    videoId: "ZYcODx-N0co",
    title: "name &#39;include&#39; is not defined in python",
    description: "name 'include' is not defined in python.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/ZYcODx-N0co/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/ZYcODx-N0co/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/ZYcODx-N0co/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 347,
    views: 562,
  },
  {
    _id: "8b718092-e549-4c01-b856-c7de3625ecca",
    category: "Something",
    videoId: "4BggBUDDO2k",
    title: "module.js:340 throw err;",
    description: "node js module.js:340 throw err;",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/4BggBUDDO2k/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/4BggBUDDO2k/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/4BggBUDDO2k/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 141,
    views: 63,
  },
  {
    _id: "1d632cb1-3ae5-4bda-b853-3e4e2defb719",
    category: "Something",
    videoId: "5cutXyRa1mQ",
    title: "Unhandled &#39;error&#39; event(node.js error)",
    description:
      "when run node.js program .then error is generated in some time.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/5cutXyRa1mQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/5cutXyRa1mQ/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/5cutXyRa1mQ/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 162,
    views: 572,
  },
  {
    _id: "972fc7b2-3e7a-4910-bbd6-ed41ae1e3e40",
    category: "Something",
    videoId: "1Qxqp5Hn8VM",
    title: "CURL extension needs to be loaded for OpenCart to work!",
    description: "CURL extension needs to be loaded for OpenCart to work!",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/1Qxqp5Hn8VM/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/1Qxqp5Hn8VM/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/1Qxqp5Hn8VM/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 73,
    views: 430,
  },
  {
    _id: "9ec12fc9-35ee-4c8c-b86a-1045cfd8843f",
    category: "Something",
    videoId: "Cf42rHgvqXk",
    title: "Invalid block tag static files",
    description: "how to remove Invalid block tag: 'static' error.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/Cf42rHgvqXk/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/Cf42rHgvqXk/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/Cf42rHgvqXk/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 416,
    views: 380,
  },
  {
    _id: "06b922b6-d3cf-48ad-b25d-5603fa57b572",
    category: "Something",
    videoId: "bE7wSmqofNs",
    title: "how to run c++ program on ubuntu terminal",
    description: "run c++ program on ubuntu terminal.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/bE7wSmqofNs/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/bE7wSmqofNs/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/bE7wSmqofNs/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 375,
    views: 560,
  },
  {
    _id: "02494b61-3e15-4f8a-9ee2-cdecdf0efad3",
    category: "Something",
    videoId: "e5kmRkYYXdM",
    title: "databases is improperly configured",
    description: "solution of settings.databases is improperly configured.",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/e5kmRkYYXdM/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/e5kmRkYYXdM/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/e5kmRkYYXdM/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 414,
    views: 507,
  },
  {
    _id: "0462aac2-73d2-4d26-8478-21565e6a5940",
    category: "Something",
    videoId: "i2GbK0o0ZDQ",
    title: "relation django site does not exist",
    description: "solution of relation django site does not exist .",
    thumnailMedium: {
      url: "https://i.ytimg.com/vi/i2GbK0o0ZDQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
    thumnailDefault: {
      url: "https://i.ytimg.com/vi/i2GbK0o0ZDQ/default.jpg",
      width: 120,
      height: 90,
    },
    thumnailHigh: {
      url: "https://i.ytimg.com/vi/i2GbK0o0ZDQ/hqdefault.jpg",
      width: 480,
      height: 360,
    },
    author: "rahul shukla",
    isWatechList: false,
    isLiked: false,
    isDisliked: false,
    videoDuration: "",
    likes: 117,
    views: 72,
  },
];
